@isTest
public with sharing class HttpResponseFileMakerTest {


    @isTest
    public static void test_makeTxtFileFromJSONResponse() {
        // make http response with json data & format
        // send to response file maker
        // check that file was made
    }

    @isTest
    public static void test_checkJSONFilePrettyFormat() {
        // check lines in created file
    }

    @isTest
    public static void test_responseFileName() {
        // check that name fits wanted name
    }
}
